server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /langfuse-api-uat/ {
        proxy_pass https://monitor-live-test-cedar.sdmc.tv/;
        proxy_set_header Host monitor-live-test-cedar.sdmc.tv;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /langfuse-api-uat-local/ {
        proxy_pass https://monitor-live-test-cedar.sdmc.tv/;
        proxy_set_header Host monitor-live-test-cedar.sdmc.tv;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /langfuse-api-test/ {
        proxy_pass https://monitor-live-test-cedar.sdmc.tv/;
        proxy_set_header Host monitor-live-test-cedar.sdmc.tv;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /langfuse-api-prod/ {
        proxy_pass https://monitor-live-test-cedar.sdmc.tv/;
        proxy_set_header Host monitor-live-test-cedar.sdmc.tv;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /langfuse-api-prod-local/ {
        proxy_pass https://monitor-live-test-cedar.sdmc.tv/;
        proxy_set_header Host monitor-live-test-cedar.sdmc.tv;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /tapd-api/ {
        proxy_pass https://api.tapd.cn/;
        proxy_set_header Host api.tapd.cn;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
