import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../scripts/adbBridge.cjs', import.meta.url), 'utf8');
const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));

assert.match(source, /LOG_SOURCE_SERIAL/);
assert.match(source, /loadSerialPort/);
assert.match(source, /listSerialPorts/);
assert.match(source, /listWindowsUsbDiagnostics/);
assert.match(source, /PowerShell USB diagnostics failed to start/);
assert.match(source, /未知 USB 设备/);
assert.match(source, /设备描述符请求失败/);
assert.match(source, /usbDiagnostics/);
assert.match(source, /detectFromSerial/);
assert.match(source, /VOICE WAKE WORD HIT ACCEPTED/);
assert.match(source, /Cedar: Input Text/);
assert.match(source, /Audio latency first_downlink_audio/);
assert.match(source, /TTS playback done/);
assert.match(source, /let listeningDetected = false;/);
assert.match(source, /listeningDetected = true;/);
assert.match(source, /wakeDetected && listeningDetected/);
assert.match(source, /SpeechService.*onLiveTtsEnd/);
assert.match(source, /DEFAULT_RESPONSE_TTS_KEYWORDS[\s\S]*TTS_STATUS[\s\S]*tts_status/);
assert.match(source, /playbackDoneMatchers[\s\S]*endMatcher/);
assert.match(source, /response\.playback_done\.detected/);
assert.match(source, /status: 'playback_done'/);
assert.match(source, /failureMatchers[\s\S]*response\.failure\.detected/);
assert.match(source, /let responseListeningDetected = false;/);
assert.match(source, /responseListeningDetected = true;/);
assert.match(source, /firstAudioDetected && playbackDoneDetected && responseListeningDetected/);
assert.match(source, /responseListeningTime/);
assert.match(source, /responseListeningLine/);
assert.match(source, /WS response timeout/);
assert.match(source, /rebootAiToyViaSerial/);
assert.match(source, /serial\.reboot\.start/);
assert.match(source, /resolveLogSource\(body\) === LOG_SOURCE_SERIAL[\s\S]*rebootAiToyViaSerial/);
assert.match(source, /looksLikeSerialDeviceId/);
assert.match(source, /normalizeSerialPath\(body\)[\s\S]*rebootAiToyViaSerial/);
assert.match(source, /resolveSerialDeviceSelection/);
assert.match(source, /probeSerialReadable/);
assert.match(source, /serial_open_failed/);
assert.match(source, /serial\.open\.failed/);
assert.match(source, /const SERIAL_PORT_LOCKS = new Map\(\);/);
assert.match(source, /async function withSerialPortLock\(serialPort, operation\)/);
assert.match(source, /SERIAL_PORT_LOCKS\.set\(lockKey, next\)/);
assert.match(source, /await previous\.catch\(\(\) => \{\}\)/);
assert.match(source, /async function closeSerialQuietly\(port\)/);
assert.match(source, /await closeSerialQuietly\(serialDevice\)/);
assert.match(source, /return withSerialPortLock\(safeSerialPort, \(\) => new Promise/);
assert.match(source, /async function collectWindowsSerialMode\(serialPort\)/);
assert.match(source, /mode \$\{safeSerialPort\}/);
assert.match(source, /serialModeDiagnostics/);
assert.match(source, /serialMode: probe\.serialModeDiagnostics/);
assert.doesNotMatch(source, /const selectedDeviceId = selectedDevice\?\.id \|\| serialPort \|\| '';/);
assert.match(source, /selectedDeviceId = selectedDevice\?\.id \|\| ''/);
assert.match(source, /USB串口不存在或已重新枚举/);
assert.match(source, /serial\.device\.reselect/);
assert.match(source, /rebootAiToyViaSerial[\s\S]*resolveSerialDeviceSelection/);
assert.match(source, /resetSerialByControlLines/);
assert.match(source, /dtr: false,\s*rts: true/);
assert.match(source, /dtr: true,\s*rts: false/);
assert.match(source, /rebootAndObserve/);
assert.equal(pkg.dependencies.serialport, '^12.0.0');
