import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('../src/hooks/useTestRunner.js', import.meta.url), 'utf8');

assert.match(source, /import \{ runAiToyTest \} from '\.\.\/runners\/aiToyRunner';/);
assert.match(source, /buildDeviceExecutionQueue/);
assert.match(source, /buildContinueDecision/);
assert.match(source, /item\.needWakeup/);
assert.match(source, /dialogueTurnKey/);
assert.match(source, /continueDecision/);
assert.match(source, /shouldContinue/);
assert.match(source, /resolveDeviceRuntimeOptions/);
assert.match(source, /deviceRuntime\.deviceType/);
assert.match(source, /deviceRuntime\.logSource/);
assert.match(source, /deviceRuntime\.serialPort/);
assert.match(source, /deviceRuntime\.baudrate/);
assert.match(source, /const isAiToyRun = deviceRuntime\.deviceType === DEVICE_TYPES\.AI_TOY/);
assert.match(source, /const isSpeakerRun = deviceRuntime\.deviceType === DEVICE_TYPES\.SPEAKER/);
assert.match(source, /if \(isAiToyRun\) \{[\s\S]*await runAiToyTest\(/);
assert.match(source, /runAiToyTest\(\{[\s\S]*playAudioItem[\s\S]*adbWakeService[\s\S]*\}\)/);
assert.match(source, /test_audio\.before_play\.check/);
assert.match(source, /test_audio\.stopped_before_play/);
assert.match(source, /stopReason:\s*resolveStopReason\(runId\)/);
assert.match(source, /adbWakeService\.detectAsr\(\{[\s\S]*signal: abortControllerRef\.current\?\.signal[\s\S]*\}\)\.catch\(\(err\) => \(\{ __error: err \}\)\)/);
assert.doesNotMatch(source, /shouldResetTtsQueueBeforeTestAudio/);
assert.doesNotMatch(source, /shouldDeferAiToyAsrUntilAudioStart/);
assert.doesNotMatch(source, /asr\.detect\.start\.after_test_audio_started/);
assert.doesNotMatch(source, /shouldDeferAiToySerialResponseLog/);
assert.doesNotMatch(source, /ai_toy\.serial_response/);
assert.doesNotMatch(source, /Speaker 已唤醒，播放测试音频/);
assert.match(source, /\$\{deviceRuntime\.profile\?\.label \|\| '设备'\} 已唤醒，播放测试音频/);
assert.match(source, /buildRetryQueueItem/);
assert.doesNotMatch(source, /&& matchesAiToyRecoverableFailure\(previousFailureEvent\)/);
assert.match(source, /rebootResult\.recoveredDeviceId/);
assert.match(source, /actions\.setDeviceOptions\(\{\s*serialPort: recoveredSerialPort\s*\}\)/);
assert.match(source, /actions\.setAutonomousWake\(\{\s*deviceId: recoveredSerialPort\s*\}\)/);
assert.match(source, /speakerContinuousDialogue/);
assert.match(source, /isSpeakerContinuousDialogue/);
assert.match(source, /lastSpeakerPlaybackDoneResult/);
assert.match(source, /continuous_speaker\.wait_for_playback_done/);
assert.match(source, /speakerSingleTurnLangfuseWakeGateEnabled/);
assert.match(source, /scheme2\.langfuse_response_timeout_continue_next_wake/);
assert.match(source, /Langfuse response_complete 获取超时，标记本轮失败并进入下一轮唤醒/);
assert.match(source, /if \(isSpeakerRun && \(autonomousResponseEnabled \|\| shouldGateNextSpeakerTurn\) && success\)/);
assert.match(source, /if \(!speakerSingleTurnLangfuseWakeGateEnabled && autonomousResponseEnabled\)/);
assert.match(source, /if \(!speakerSingleTurnLangfuseWakeGateEnabled\)/);
assert.match(source, /if \(!isLastCase && nextItem\?\.needWakeup !== false && isSpeakerRun && autonomousResponseEnabled && !speakerSingleTurnLangfuseWakeGateEnabled\)/);
assert.match(source, /if \(!isLastCase && speakerSingleTurnLangfuseWakeGateEnabled\)/);
assert.match(source, /continuous_speaker\.reboot_requires_rewake/);
